/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2020-07-17 14:10:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Entrar</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"jQuery Mask/jquery.mask.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\" integrity=\"sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Raleway\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"bootstrap\\css\\bootstrap.min.css\" />\r\n");
      out.write("<link rel='stylesheet' href='style.css' />\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"img/ico.png\">\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: 'SST W01 Roman','SST W02 Roman','SST W10 Roman','SST W15 Roman',Arial,Helvetica,sans-serif;\r\n");
      out.write("        background-image: url(img/backlogin.jpg);\r\n");
      out.write("        background-repeat: no-repeat;\r\n");
      out.write("        background-position: center;\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("        background-repeat: no-repeat;\r\n");
      out.write("        height: 90vh;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    a {\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    a:link{\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    a:hover{\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: white\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #loginG {\r\n");
      out.write("        color: #ff1040;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    * {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        outline: none;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        font-family: 'Raleway', sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .cont {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        width: 25%;\r\n");
      out.write("        height: 400px;\r\n");
      out.write("        padding: 10px 25px;\r\n");
      out.write("        margin: 10vh auto;\r\n");
      out.write("        background: #1e1e26;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h1,\r\n");
      out.write("    h2,\r\n");
      out.write("    .user,\r\n");
      out.write("    .pass {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h1 {\r\n");
      out.write("        color: #ff1040;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        font-size: 40px;\r\n");
      out.write("        margin: 30px auto;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .user,\r\n");
      out.write("    .pass,\r\n");
      out.write("        .login {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            font-weight: lighter;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    .user,\r\n");
      out.write("    .pass {\r\n");
      out.write("        background: #ecf0f1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login {\r\n");
      out.write("        color: white;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        background: #ff1040;\r\n");
      out.write("        transition: 0.4s ease;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input {\r\n");
      out.write("        color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .back {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 45px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        font-weight: lighter;\r\n");
      out.write("      \r\n");
      out.write("        color: white;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("     \r\n");
      out.write("        background: #ff1040;\r\n");
      out.write("        transition: 0.4s ease;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login:hover {\r\n");
      out.write("        background: #ff0033;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .back:hover {\r\n");
      out.write("        background: #ff0033;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    @media only screen and (min-width : 50px) {\r\n");
      out.write("        .cont {\r\n");
      out.write("            width: 300%\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media only screen and (min-width : 280px) {\r\n");
      out.write("        .cont {\r\n");
      out.write("            width: 90%\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media only screen and (min-width : 480px) {\r\n");
      out.write("        .cont {\r\n");
      out.write("            width: 60%\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media only screen and (min-width : 768px) {\r\n");
      out.write("        .cont {\r\n");
      out.write("            width: 40%\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media only screen and (min-width : 992px) {\r\n");
      out.write("        .cont {\r\n");
      out.write("            width: 30%\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h2 {\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        margin-top: 25px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		String cpf = request.getParameter("cpf");
		String result = request.getParameter("result");
		String urlIO = "1a48c08e71bf.ngrok.io";
		if(result != null){
			if(result.equals("right")){
	
      out.write("\r\n");
      out.write("\t\t<div class=\"alert alert-danger\" align=\"center\">\r\n");
      out.write("\t\t\tParabéns, você foi cadastrado(a) com sucesso!\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t");
	
			}else if(result.equals("wrong")){
	
      out.write("\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t \talert(\"Erro ao cadastrar, informações preenchidas incorretamente.\");\r\n");
      out.write("\t\t \twindow.location.href = \"http://\"+b632ee66b82e.ngrok.io+\"/EventCreator/cad.jsp\";\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t");
			
			}else if(result.equals("wrongCpf")){
	
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t \talert(\"CPF inválido.\");\r\n");
      out.write("\t\t \twindow.location.href = \"http://\"+b632ee66b82e.ngrok.io+\"/EventCreator/cad.jsp\";\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t");
			
				
			}else if(result.equals("wrongpassword")){
	
      out.write("\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t \talert(\"Senhas incorretas.\");\r\n");
      out.write("\t\t \twindow.location.href = \"http://\"+b632ee66b82e.ngrok.io+\"/EventCreator/cad.jsp\";\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t");
		
			}else if(result.equals("length")){
	
      out.write("\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t \talert(\"Tamanho do CPF ou telefone incorretos.\");\r\n");
      out.write("\t\t \twindow.location.href = \"http://\"+b632ee66b82e.ngrok.io+\"/EventCreator/cad.jsp\";\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t");

			}else if(result.equals("wrongLog")){
	
      out.write("\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t \talert(\"CPF ou senha inválidos.\");\r\n");
      out.write("\t\t \twindow.location.href = \"http://\"+b632ee66b82e.ngrok.io+\"/EventCreator/login.jsp\";\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t");
		
			}else{
	
      out.write("\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t \talert(\"Ocorre algum erro, tente novamente.\");\r\n");
      out.write("\t\t \twindow.location.href = \"http://l\"+b632ee66b82e.ngrok.io+\"/EventCreator/cad.jsp\";\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t");
			
			}
				
		}
	
      out.write("\t\r\n");
      out.write("\t");
 String whois = (session.getAttribute("user") == null) ? "nobody" : session.getAttribute("user").toString();
      out.write("\r\n");
      out.write("\t<div class=\"cont\">\r\n");
      out.write("        <div class=\"form\">\r\n");
      out.write("\t\t\t<form method=\"POST\" action=\"process\">\r\n");
      out.write("\t\t\t    ");
if(whois.equals("nobody")){ 
      out.write("\r\n");
      out.write("\t\t\t    \t<h1 id=\"loginG\">LOGIN</h1>\r\n");
      out.write("\t\t\t    \t");
 if(cpf != null){ 
      out.write("\t\t    \t\t\r\n");
      out.write("\t\t\t\t    \t<input type=\"text\" class=\"user\" name=\"cpf\" value=\"");
      out.print(cpf );
      out.write("\" placeholder=\"CPF\" required minlength=\"11\" maxlength=\"11\" id=\"cpfzao\"/>\r\n");
      out.write("\t\t\t\t    ");
}else { 
      out.write("\r\n");
      out.write("\t\t\t\t    \t<input type=\"text\" class=\"user\" name=\"cpf\" placeholder=\"CPF\" required minlength=\"11\" maxlength=\"11\" id=\"cpfzao\"/>\r\n");
      out.write("\t\t\t\t    ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t    <input type=\"password\" class=\"pass\" name=\"senha\" placeholder=\"SENHA\" required minlength=\"3\"/>\r\n");
      out.write("\t\t\t    \t<input type=\"hidden\" name=\"log\" value=\"true\">\r\n");
      out.write("\t\t\t    \t<button class=\"login\">ENTRAR</button>\r\n");
      out.write("\t\t\t    ");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t    \t<input type=\"hidden\" name=\"log\" value=\"false\">\r\n");
      out.write("\t\t\t    \t<button class=\"login mt-5 mb-5\">SAIR</button>\r\n");
      out.write("\t\t\t    ");
} 
      out.write("\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    <input type=\"hidden\" name=\"action\" value=\"auth\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<button class=\"btn back mt-1\"><a href=\"home.jsp\">VOLTAR</a></button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script src=\"cadjs.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
