/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2020-07-16 23:47:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.*;
import java.io.*;
import org.json.*;
import java.lang.Object.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("org.json");
    _jspx_imports_packages.add("java.lang.Object");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Perfil</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"img/ico.png\">\r\n");
      out.write("<script src=\"js\\jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"bootstrap\\css\\bootstrap.min.css\" />\r\n");
      out.write("<script src=\"bootstrap\\js\\bootstrap.min.js\"></script>\r\n");
      out.write("<link rel='stylesheet' href='profile.css' />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"path/to/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("<script src=\"https://use.fontawesome.com/526c112d9c.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
 	String whois = (session.getAttribute("user") == null) ? "nobody" : session.getAttribute("user").toString(); 
		
	if(!whois.equals("nobody")){ 
		JSONObject ob = new JSONObject(whois);
		JSONObject obj = ob.getJSONObject("Users");
		String foto = obj.getString("uri");
		
      out.write("\r\n");
      out.write("\t<div class=\"main-container\">\r\n");
      out.write("        <header class=\"block\">\r\n");
      out.write("            <ul class=\"header-menu horizontal-list\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a class=\"header-menu-tab\" href=\"home.jsp\"><span class=\"icon fontawesome-user scnd-font-color\"></span>Página inicial</a>\r\n");
      out.write("                </li>\r\n");
      out.write("             \t\r\n");
      out.write("                <li>\r\n");
      out.write("                \t<form method=\"POST\" action=\"process\">\r\n");
      out.write("                \t\t<input type=\"hidden\" name=\"action\" value=\"auth\" />\r\n");
      out.write("\t\t\t    \t\t<input type=\"hidden\" name=\"log\" value=\"false\" />\r\n");
      out.write("                    \t<button class=\"header-menu-tab btn\" type=\"submit\" style=\"color: white;\"><span class=\"icon fontawesome-remove scnd-font-color\"></span>Sair da conta</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    \r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"profile-menu\">\r\n");
      out.write("                <p id=\"nome\">");
      out.print(obj.getString("nome") );
      out.write("<a href=\"#26\"></a></p>\r\n");
      out.write("                <div class=\"profile-picture small-profile-picture\">\r\n");
      out.write("                    <img width=\"40px\" src=\"http://187.111.222.107:3516/files/");
      out.print(foto );
      out.write("\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"left-container container\">\r\n");
      out.write("            <div class=\"menu-box block\">\r\n");
      out.write("                <h2 class=\"titular\">MENU</h2>\r\n");
      out.write("                <ul class=\"menu-box-menu\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"menu-box-tab\" href=\"cadPart.jsp\"><span class=\"icon entypo-cog scnd-font-color\"></span>Configuração de time</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"menu-box-tab\" href=\"partEvent.jsp\"><span class=\"icon entypo-trash scnd-font-color\"></span>Sair de evento</a>\r\n");
      out.write("                    </li>                        \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("        <div class=\"middle-container container\">\r\n");
      out.write("            <div class=\"profile block\" style=\"width: 300px; padding-top: 2rem;\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"profile-picture big-profile-picture clear\" >\r\n");
      out.write("                    <img width=\"150px\" alt=\"Anne Hathaway picture\" src=\"http://187.111.222.107:3516/files/");
      out.print(foto );
      out.write("\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                <h1 class=\"user-name\" id=\"nome\">");
      out.print(obj.getString("nome") );
      out.write("</h1> \r\n");
      out.write("                <h1 class=\"user-name\" id=\"Cidade\">");
      out.print(obj.getString("cidade") );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(obj.getString("estado") );
      out.write("</h1>\r\n");
      out.write("                <a class=\"add-event button\" href=\"cadEvent.jsp\">Criar Evento</a>\r\n");
      out.write("            </div>\r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"right-container container\">\r\n");
      out.write("            <div class=\"calendar-day block\">  \r\n");
      out.write("                    <p class=\"the-day\" style=\"padding-top: 2rem;\">Veja os eventos disponiveis!</p>\r\n");
      out.write("                    <div style=\"border-bottom: 6rem solid transparent;\"></div>\r\n");
      out.write("                    <a class=\"add-event button\" href=\"partEvent.jsp\">Participar de evento</a>\r\n");
      out.write("            </div>\r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
}else{
      out.write("\r\n");
      out.write("    \t<script>window.location.href = \"http://localhost:8080/EventCreator/login.jsp\";</script>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
